### ISSUE TITLE
Improve the experience of navigating between the home page and not-home page in the  Twenty-seventeen theme

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#11]
As a Twenty-seventeen-westonson viewing the theme at CDS, I'd like to see an improved experience navigating between the home page and not-home page.
 - [x] _AC 1:_ Improve the user experience navigating between the homepage and not-homepage in the Twenty-seventeen-westonson child theme:
 - [x] _AC 2:_  create a better transition navigating between the between the homepage and not-homepage and resolve the issue described here (From @westonruter) 
      - The homepage has a full screen header image, and the non-home pages have a short header. We need to transition between the two in a way that isn't abrupt. See for example:  https://app-shell-westonruter.pantheonsite.io/ and navigate to one of the other nav menu items, and go back

**Comment by cathibosco** [comment]
A minimal header with a dynamic hero might be a good solution. If this seems valid I can mock it up more hi if and create a simple animation or more dynamic hero presentation for the home page.

See the low-fi sketch attached.

Minimal (sticky possibly) header and one column presentation would make a big difference and potentially would not be too complicated to customize. (?)

Here is a link to a layout that we could customize 2017 to be more like. It tends to work with a lot of different types of sites too.  https://powerphone.com/
![customization suggestion pwa](https://user-images.githubusercontent.com/4819761/47724351-e1d05a00-dc2c-11e8-9c8d-9c662910ba34.jpg)

**Comment by cathibosco** [comment]
I was suggesting the above option… however, I better understand now that the header is a “feature”  (to have the different header styles) and is critical to showcase. Working up a sketch for it..

**Comment by alcurrie** [comment]
From @jwold  notes from Weston to use 2017 theme: 
**1. Header stuff**
- Biggest design thing needed for 2017: when you navigate from homepage (with big home screen image) to contact page (header changes size).
- It’s a feature to have the different header styles, even in Serma’s demo it’s helpful to show going from home > single post with a header that transitions.
- If header can animate change in its height?
- Or maybe homepage doesn’t have taller header.
- We need to transition between pages with something better.

**2. Instead of Weston Ruter site, maybe about Oregon mountain, mt Jefferson. Jefferson Wisdom** :slightly_smiling_face:
**3. Improve design of header image and messaging and purpose of site for a better demo.**

**Comment by miina** [comment]
Closing this since the Animation seems to be done.
