### ISSUE TITLE
Resolve issues with menu navigation and pages displaying blank in Safari

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#15]
**Test steps**
1.  Navigate to the CDS theme site in Safari: https://dev-showcase-pwa.pantheonsite.io/
2. Click/Tap on the any of the menu items other than the home page

**Expected**
User is redirected to the About, Services, or Blog page and the page content displays in Safari ie. header and page content below. (Works in Chrome) 

**Actual**
The user is not redirected to the page, and the content on the page shows as blank: https://cl.ly/8637dcca42f8

**Comment by alcurrie** [comment]
@miina  - this is the JS issue that was discussed on Slack.  NB: I've confirmed this is also an issue in iOS (Mobile) for both Safari and Chrome

**Comment by miina** [comment]
@alcurrie This issue should be fixed now.
