### ISSUE TITLE
Resolve issues with Mobile Display AMP / Non AMP

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#16]
_Test steps_
Navigate to  Non- AMP Home, About, Services and Blog, on the https://dev-showcase-pwa.pantheonsite.io/ site
Confirm display and functionality, and menu navigation  in mobile
Navigate to  AMP Home, About, Services and Blog, on the https://dev-showcase-pwa.pantheonsite.io/ site
Confirm display and functionality, and menu navigation  in mobile
Confirm that AMP and Non-AMP have display and feature Parity

**Expected**
AMP and Non-AMP have display and feature Parity and should display and work as designed.

**Actual**
_Mobile (iPhone 7 -Safari  iOS11)_
**_Home_  - Non-AMP**
1)  Header is not animated and does not ‘shrink up’
2) Neither the header (as in desktop) nor the ‘menu’ is persistent on mobile (menu is persistent in desktop)
3)  Visually, the top circle image and images from ‘columns’ are still slightly off center in mobile.
https://cl.ly/93cf905ae552
**_Home_  -  AMP**
1 and 2 same as non-AMP,
3)  All the circle images are more significantly not centred ie. shifted left or right and there is not enough space/padding between the circle image and the heading below.
https://cl.ly/573f15ba01cb
As reported in #15 in iOS Mobile 

_Mobile Chrome (iOS 11) _
**_Home -AMP_** 
Same issues reported above (1, 2, and 3)  for Safari apply to Mobile Chrome in (iOS 11)
https://cl.ly/e06390436366

**_About - Non-AMP_**
Too much spacing around video
https://cl.ly/247be89a31fa

Mobile Chrome (Google Pixel 2 - Android 9)
_**Home - Non-AMP**_
1)  Header is not animated and does not ‘shrink up’
2) Neither the header (as in desktop) nor the ‘menu’ is persistent on mobile (menu is persistent in desktop)
3)  Visually, the top circle image and images from ‘columns’ are still slightly off center in mobile.
4) Menus expand and overall work as expected, except that on clicking to expand the menu, the top of the list of menu options does not move up so the menu is visible in the viewport. It works but it's not a great user experience.
https://cl.ly/a29d4f438f53

Mobile Chrome (Samsung Galaxy S9- Android 8)
**_Home -AMP_** 
Same issues reported above (1, 2, and 3) but the issues with the  top circle image and images from ‘columns’ are more significant in mobile AMP
As reported in  Non-AMP _4) Menus expand and overall work_ but it's not a great user experience. 
Same issues apply for AMP - About, Services, Blog
https://cl.ly/4cbc564a367e

NB: for this 'Google and Samsung Android devices - the navigation issues reported for iOS #15 in iOS   do not apply.

**Comment by bluestormcreative** [comment]
1. I am seeing the header animate as intended so it's possible this was a caching issue? I'm not able to recreate locally or on a live device (also iPhone 7, and Google Pixel 2)

2. I am seeing persistent headers and menus on mobile, however we should push a change to close the mobile menu on click/tap while the content does its seamless refresh.

3. and 4. I've pushed changes that should better center the circle images overall, but will still need to check and test AMP vs non-AMP for parity in this and with the other issues noted above.

**Comment by mehigh** [comment]
@alcurrie / @bluestormcreative from the discussions on Slack things seem to have arrived in a good state. Flag me directly if there's anything here needing my attention.

**Comment by alcurrie** [comment]
Confirmed updates to Mobile design and Mobile is displaying as expected:
**Home:** https://cl.ly/725692e4561e
**About:** https://cl.ly/20f310422c1e
