### ISSUE TITLE
Make twentyseventeen-westonson child theme Paired AMP with no compatibility tool or AMP validation errors

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#3]
As a site owner, deciding to use twentyseventeen-westonson child theme on my site, I'm expecting that it will be Paired AMP and will not surface any compatibility errors  on activation

- [x] AC1: This child theme will be Paired AMP by default
- [x] AC2: On activation of the theme - no errors will surfaced by the compatibility tool
- [x] AC3: Theme templates, posts, pages, archives, etc will display without AMP validation errors.

**Comment by westonruter** [comment]
> The AC1 says that the theme should be Native AMP by default, at this moment the theme has AMP support set up and is in Paired mode -- is that's how it should be? I remember you mentioning verbally in one of the calls that the site should be in Paired mode. Just wanted to confirm if there's anything to do here from our side or if it is as it should be;

Correct. It should now be paired mode instead, so this is done.

> There are some rows displayed on the "AMP Validated URLs" page, however, these aren't showing any details in the "Invalid" column. Also, under "AMP Validation Error Index" no URLs are listed under "Found URLs" and all the errors are "Accepted". Is this as expected or is there anything else we should do about the rows listed in the Compatibility Tool?

On https://dev-showcase-pwa.pantheonsite.io/wp-admin/edit.php?post_type=amp_validated_url&paged=1 I'm seeing:

![image](https://user-images.githubusercontent.com/134745/48148159-fbe1ec00-e26d-11e8-9fad-b027783a0ab0.png)

I'm confused as to why it is listing “Twenty Seventeen Westonson (?)” as the source, when there apparently there are zero validation errors for the given URL:

![image](https://user-images.githubusercontent.com/134745/48148196-13b97000-e26e-11e8-9c9f-b7aeb9af2a81.png)

So that is not expected.

**Comment by westonruter** [comment]
@miina I've identified the problem. Fix in https://github.com/Automattic/amp-wp/commit/76dd089376bcf46b98f51865ead3398213cc2702

**Comment by westonruter** [comment]
Opened pull request for 1.0 branch: https://github.com/Automattic/amp-wp/pull/1592

**Comment by alcurrie** [comment]
Thanks for the updates to the AC  @miina  and @westonruter. This will likely be resolved with the updates in the pull request, but I did want to flag that as of now an paired mode I'm seeing the following 2 discrepancies between AMP and non AMP (though the AMP pages I checked are validating) 
In AMP the top circular image on the home page is smaller on AMP and the SoundCloud embed is condensed.  https://cl.ly/acb249facc7e

**Comment by westonruter** [comment]
The difference in appearance of the SoundCloud embed is OK. The difference in the image should be looked at, however. May be due to issues with `layout` and `sizes` in AMP.

**Comment by miina** [comment]
Closing this since the tasks here seem to be done, differences between AMP and non-AMP were logged in a separate ticket (#16).

@alcurrie Let me know if there's anything you find / found that still needs to be addressed.

**Comment by alcurrie** [comment]
@miina  and @westonruter All looks good. The mobile issues were resolved (with screencasts) in #16 

And I revalidated the AMP on all the pages: See:  https://cl.ly/6aa420063d50

Also, per discussion above, there are no unaccepted AMP Validated URLs: https://cl.ly/cc56467c67c2

Based on this, I'm moving this issues to Done
