### ISSUE TITLE
Extend the existing [twentyseventeen] [westonson]  child theme to engage user interest and showcase PWA, AMP, and other new features being rolled out

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#5]
As a conference attendee, I'd like the demo site to have a clean, elegant and playful design, so  that I can see, understand and appreciate the benefits of using the features  being demo'd on my own web site.
 [ ] _AC1:_ Building on the [twentyseventeen] [westonson] child theme create a custom design for the demo site that will be clean, elegant and playful
         - [ ] New design for the home page and static page design here: https://d.pr/i/vfyGN2
          ![topgraphicdesign_homestaticpage](https://user-images.githubusercontent.com/18579988/48037895-4f541d00-e13c-11e8-8cc3-3dd6d4fff7f0.png)
         - [ ] Design will be built using the design resources for the approved design here: https://drive.google.com/open?id=1S3q0KTQEIQkxv6S8xiPOWUPCIxzd2YDo
 [ ] _AC2:_  The theme should showcase/highlight the new features being demo'd
         - [ ] AMP Plugin
         - [ ] Compatibility tool
         - [ ] PWA
         - [ ] Offline Commenting
 [ ] _AC3:_  The home page design will include a header animation: 
         - [ ]   Header (including title, logo and tagline at 75% size) animate up    
         - [ ] After the header has animated up to it's final state, the logo/title/tagline enlarge to their 100% size.
  [ ] _AC4:_  The implementation of the header animation will follow the recommendation/model of https://pwp.dassur.ma/ and will not animate the `height` CSS property but instead look at an alternative to `height`, such as animating the `transform`  property.

**Comment by alcurrie** [comment]
@bluestormcreative  - I did not add the comments discussions from Slack this afternoon to this issue as I think you are already part of that discussion, but I can do if that would be helpful.

**Comment by miina** [comment]
Closing this since it seems to be Done.
