### ISSUE TITLE
Add enhanced streaming for loading heavy content 

### ISSUE THREAD

**Issue by alcurrie** [westonruter/twentyseventeen-westonson#6]
**As a site visitor, I'd like streaming to work in the existing theme so that transitions are smooth and heavy content pages start to load almost instantly.**
- [ ] _AC1:_  Streaming/Transitioning will be added to the theme and should work without error in AMP (included Paired and Native AMP)

**Related to**: https://github.com/xwp/pwa-wp/issues/90

**Comment by alcurrie** [comment]
Updated AC to remove requirement for enhanced streaming  transitions to the twentyseventeen-westonson theme (e.g. [Gutenberg's skeleton content](https://github.com/WordPress/gutenberg/pull/10613)

**Comment by alcurrie** [comment]
@westonruter  - you identified  for @jwold  that this is the code to implement streaming in a theme. I'm adding it here for context.
• `add_theme_support(...)`: https://github.com/westonruter/twentyseventeen-westonson/blob/293443b0c5dc4bed296d6d45024b78a0316e496a/functions.php#L41
• Vary precached header revision by what populates it: https://github.com/westonruter/twentyseventeen-westonson/blob/293443b0c5dc4bed296d6d45024b78a0316e496a/functions.php#L48-L68
• Call the stream boundary function: https://github.com/westonruter/twentyseventeen-westonson/blob/293443b0c5dc4bed296d6d45024b78a0316e496a/template-parts/header/site-branding.php#L131-L134

**Comment by jwold** [comment]
At this stage it's just a matter of illustrating the concept. Weston and myself discussed this yesterday. No more code work is needed. 

The skeleton idea discussed previously we can reserve for App Shell.

**Comment by alcurrie** [comment]
Per discussion in Slack, final task to complete this issue, is to create the skeleton content that appears initially in an app shell context. This could be simply an SVG that has gray boxes for where content will probably appear.

Per discussion in Slack #pwa  this is the link with the SVG files as discussed:  https://drive.google.com/drive/folders/1xmzAT7ExmzWGGzchg8HQiP4YneEzMeg2?usp=sharing
